#!/usr/bin/env python
import re, sys, os

def main():
    # example:
    # feat(apikey): added the ability to add api key to configuration
    try:
        pattern = r'(build|ci|docs|feat|fix|perf|refactor|style|test|chore|revert)(\([\w\-]+\))?:\s.*'
        m = re.match(pattern, ss)
        if m == None:
            raise Exception("conventional commit validation failed") 
    except Exception as e:
        print(e)
        exit(1)

if __name__ == "__main__":
    main()
