# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '{{cookiecutter.projectName}}' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for {{cookiecutter.projectName}}
  
  # Code Quality
  pod 'SwiftLint'

  # Helpers
  pod 'R.swift'

  target '{{cookiecutter.projectName}}Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '{{cookiecutter.projectName}}UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
