#!/usr/bin/env python
import re, sys, os

def main():
    # examples:
    # feat(login): added the ability to log in, into the application
    # feat(login/XXX-123): Login button implementation
    # fix(XXX-123): Fix bug in login mechanism
    # chore: Add file
    try:
        pattern = r'(feat|fix|docs|style|refactor|perf|test|chore|revert)(\(\S+\))?:\s.*'
        filename = sys.argv[1]
        ss = open(filename, 'r').read()
        m = re.match(pattern, ss)
        if m == None:
            raise Exception("conventional commit validation failed")
    except Exception as e:
        print(e)
        print("Examples: \nfeat(login): added the ability to log in\nfeat(login/XXX-123): Login button implementation\nfix(XXX-123): Fix bug in login mechanism\nchore: Add file")
        exit(1)         

if __name__ == "__main__":
    main()
